# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 336e635918bf4cf7209ca181a92dc50426eac0e415f56813567114a15dfaeb750245894410cd604c4aeb531354f3adbe94aba92ac55f1a924b6d823a3a63185a

test:
  secret_key_base: 2a3786f18d82cd355ae8cc1afada91ae45ba4d75c3e6d53584bac6f07deec7309588ef4aad2895bb4cbeabe02bacc5bb925e760dc9e53b9194ad2a919cc3e171

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
